#lang racket
(require 2htdp/universe "conway.rkt" "render.rkt" "parser.rkt" "hangar.rkt")
(define grid (grid-expand (rle->grid (car (dict-ref hangar "gosper glider gun"))) 64 64))
(define play-state #t)
(define file-state #f)
(define (tick-expr world)
	(if play-state (set! grid (grid-next grid)) (void))
		world)
(define (replace l n m)
	(list-set l n (m (list-ref l n))))
(define (mouse-expr world x y type)
	(if (mouse=? type "button-down") (set! grid (replace grid (quotient y size) (lambda (R) (replace R (quotient x size) (lambda (x) (- 1 x)))))) (void))
	world)
(define (show-hangar)
	(void (map (lambda (x) (displayln (car x))) hangar)))
(define (get-hangar)
	(define input (read))
	(if (and (number? input) (< 0 input) (> (length hangar) input))
	(list-ref hangar input) (void)))
(define (key-expr world type)
	(cond
		[(key=? type "p") (set! play-state (not play-state))]
		[(key=? type "c") (set! grid (grid-expand '() (length (car grid)) (length grid)))]
		[(key=? type "l") (show-hangar)]
		[(key=? type "o") (get-hangar)])
	world)
(define (draw-expr world)
	(grid-draw grid))
(define name-expr "Conway's Game of Life Simulator")
(display "Welcome to Simulator!\n")
(display "Instructions:\n")
(display " * Press P to toggle the simulation between play/pause\n")
(display " * Press O and a number to import a patch from hangar\n")
(display " * Press L to list out the hanger patches")
(display " * Click a cell to toggle between live/dead\n")
(display "Enter \"Alelelele\" and hit enter to enter: ")
(define input (read))
(if (equal? input 'Alelelele)
	(begin
		(big-bang (void)
  		(on-tick tick-expr 0.25)
  		(on-mouse mouse-expr)
			(on-key key-expr)
  		(to-draw draw-expr)
			(name name-expr)))
	(begin
		(display "U typed \"")
		(display input)
		(display "\". Ur mom gay.\n")))
